name: Build PDF-Equilibrist

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install Dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y libpoppler-cpp-dev
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install poppler
          fi

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build
